<a href="https://colab.research.google.com/github/hdomin/Python/blob/main/07_Operaciones_con_DataFrames.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Operaciones con Data Frames

In [1]:
import numpy as np
import pandas as pd

Creamos un conjunto de datos imaginario.

A la función DataFrame, se agrega el arreglo "index" que reemplazará los valores correlativos que se generan de forma automática.

In [21]:
index = [ 'Deportivo Suchitepéquez', 'Cremas', 'Rojos', 'Juventud Retalteca']

df = pd.DataFrame( { 
    'Minutos Jugados': [ 90, 80, 100, 95],
    'Goles': [ 4, 2, 1, 2]
}, index = index)

df

                         Minutos Jugados  Goles
Deportivo Suchitepéquez               90      4
Cremas                                80      2
Rojos                                100      1
Juventud Retalteca                    95      2

Si agregamos más índices obtenemos

In [22]:
index.extend(['Deportivo Marquense', 'Petapa'])

df = df.reindex(index)
df

                         Minutos Jugados  Goles
Deportivo Suchitepéquez             90.0    4.0
Cremas                              80.0    2.0
Rojos                              100.0    1.0
Juventud Retalteca                  95.0    2.0
Deportivo Marquense                  NaN    NaN
Petapa                               NaN    NaN

En algunas ocaciones es necesario convertir el "index" a una columna.

In [25]:
df = df.reset_index()
df

                     index  Minutos Jugados  Goles
0  Deportivo Suchitepéquez             90.0    4.0
1                   Cremas             80.0    2.0
2                    Rojos            100.0    1.0
3       Juventud Retalteca             95.0    2.0
4      Deportivo Marquense              NaN    NaN
5                   Petapa              NaN    NaN

La operación inversa, convertir una columna en el "index" es:

In [27]:
df = df.set_index('index')
df

                         Minutos Jugados  Goles
index
Deportivo Suchitepéquez             90.0    4.0
Cremas                              80.0    2.0
Rojos                              100.0    1.0
Juventud Retalteca                  95.0    2.0
Deportivo Marquense                  NaN    NaN
Petapa                               NaN    NaN

Ahora agregaremos una nueva columna, sus colores

In [45]:
#df = df.drop(['Color'], axis=1)
df.insert( loc=2, column='Color', 
          value=['(Blanco|Azul|Verde)', '(Blanco|Negro)', '(Rojo|Verde)', '(Amarillo|Negro)', '(Amarillo|Negro|Verde)', '(Verde)'] )

df

                         Minutos Jugados  Goles                   Color
index
Deportivo Suchitepéquez             90.0    4.0     (Blanco|Azul|Verde)
Cremas                              80.0    2.0          (Blanco|Negro)
Rojos                              100.0    1.0            (Rojo|Verde)
Juventud Retalteca                  95.0    2.0        (Amarillo|Negro)
Deportivo Marquense                  NaN    NaN  (Amarillo|Negro|Verde)
Petapa                               NaN    NaN                 (Verde)

Una función útil es separar las cadenas

In [53]:
df['Color'] = df['Color'].str.strip('(')
df['Color'] = df['Color'].str.strip(')')
df['Color'].str.split('|')

index
Deportivo Suchitepéquez       [Blanco, Azul, Verde]
Cremas                              [Blanco, Negro]
Rojos                                 [Rojo, Verde]
Juventud Retalteca                [Amarillo, Negro]
Deportivo Marquense        [Amarillo, Negro, Verde]
Petapa                                      [Verde]
Name: Color, dtype: object

Una forma de representar los datos de forma agrupada es utilizando .stack() o. unstack()

In [55]:
df.stack()

index
Deportivo Suchitepéquez  Minutos Jugados                    90.0
                         Goles                               4.0
                         Color                 Blanco|Azul|Verde
Cremas                   Minutos Jugados                    80.0
                         Goles                               2.0
                         Color                      Blanco|Negro
Rojos                    Minutos Jugados                   100.0
                         Goles                               1.0
                         Color                        Rojo|Verde
Juventud Retalteca       Minutos Jugados                    95.0
                         Goles                               2.0
                         Color                    Amarillo|Negro
Deportivo Marquense      Color              Amarillo|Negro|Verde
Petapa                   Color                             Verde
dtype: object

In [60]:
df.unstack()

                 index
Minutos Jugados  Deportivo Suchitepéquez                    90.0
                 Cremas                                     80.0
                 Rojos                                     100.0
                 Juventud Retalteca                         95.0
                 Deportivo Marquense                         NaN
                 Petapa                                      NaN
Goles            Deportivo Suchitepéquez                     4.0
                 Cremas                                      2.0
                 Rojos                                       1.0
                 Juventud Retalteca                          2.0
                 Deportivo Marquense                         NaN
                 Petapa                                      NaN
Color            Deportivo Suchitepéquez       Blanco|Azul|Verde
                 Cremas                             Blanco|Negro
                 Rojos                                Rojo|Verde
                 Juventud Retalteca               Amarillo|Negro
                 Deportivo Marquense        Amarillo|Negro|Verde
                 Petapa                                    Verde
dtype: object